stages:
  - build
  - deploy

    #variables:
    #STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

build:
  stage: build
  image: fpco/stack-build:lts-22
  timeout: 2h
  cache:
    paths:
      - .stack
      - .stack-work
      - .stack-root
      - target
  script:
    - stack test --system-ghc --test-arguments="--profile"
  artifacts:
    paths:
      - gitlab-api-test/test_resources/
      - gitlab-api-test/sydtest-profile.html

pages:
  stage: deploy
  image: node:lts-alpine
  script:
    - npm install -g @redocly/cli
    - redocly build-docs -o public/index.html gitlab-api-test/test/resources/api/openapi.json
  artifacts:
    paths:
      - public
  only:
    - main
