stages:
  - build
  - deploy

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

build:
  stage: build
  image: haskell:9.4.8
  timeout: 2h
  cache:
    paths:
      - .stack
      - .stack-work
      - .stack-root
      - target
  script:
    - stack test --test-arguments="--profile"
  artifacts:
    paths:
      - gitlab-api-test/test/resources/
      - gitlab-api-test/sydtest-profile.html

pages:
  stage: deploy
  image: node:latest
  script:
    - npm install -g @redocly/cli
    - redocly build-docs -o public/index.html gitlab-api-test/test/resources/api/openapi.json
  artifacts:
    paths:
      - public
  only:
    - main
