resolver: lts-22.33

packages:
  - gitlab-api-http-client
  - gitlab-api-http-client-mtl
  - gitlab-api-types
  - gitlab-api-servant
  - gitlab-api-test

extra-deps: []

system-ghc: true

ghc-options:
  $everything: -split-sections
