name: gitlab-api-test
version: 0.0.0.1
github: "L7R7/gitlab-api"
license: BSD3
author: "Leonhard Riedißer"
maintainer: "leo008180@googlemail.com"
copyright: "2023 Leonhard Riedißer"
language: GHC2021

extra-source-files:
  - test_resources/**/*

description: Please see the README on GitHub at <https://github.com/L7R7/gitlab-api#readme>

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wpartial-fields
  - -Wmissing-deriving-strategies
  - -Wunused-packages
  - -Wmissing-export-lists

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - DerivingStrategies
  - DerivingVia
  - OverloadedStrings

tests:
  test:
    main: Main.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wno-missing-export-lists
      - -Wno-partial-type-signatures
    default-extensions:
      - DataKinds
    dependencies:
      - gitlab-api-types
      - gitlab-api-servant
      - autodocodec
      - autodocodec-openapi3
      - extra
      - genvalidity-scientific
      - genvalidity-sydtest
      - genvalidity-sydtest-aeson
      - genvalidity-text
      - genvalidity-time
      - genvalidity-path
      - http-client
      - http-client-tls
      - http-types
      - network-uri
      - openapi3
      - path
      - servant-client
      - servant-openapi3 >= 2.0.1.5
      - servant-server
      - sydtest
      - sydtest-aeson
      - time

